// Generated by rstantools.  Do not edit by hand.

/*
    lavaan.srm is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    lavaan.srm is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with lavaan.srm.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#include <rstan/rstaninc.hpp>
// Code generated by Stan version 2.21.0
#include <stan/model/model_header.hpp>
namespace model_RR_con_comp_g1_namespace {
using std::istream;
using std::string;
using std::stringstream;
using std::vector;
using stan::io::dump;
using stan::math::lgamma;
using stan::model::prob_grad;
using namespace stan::math;
static int current_statement_begin__;
stan::io::program_reader prog_reader__() {
    stan::io::program_reader reader;
    reader.add_event(0, 0, "start", "model_RR_con_comp_g1");
    reader.add_event(23, 23, "include", "/means/means_data.stan");
    reader.add_event(23, 0, "start", "/means/means_data.stan");
    reader.add_event(25, 2, "end", "/means/means_data.stan");
    reader.add_event(25, 24, "restart", "model_RR_con_comp_g1");
    reader.add_event(36, 35, "include", "/vanilla/tdata_allKd.stan");
    reader.add_event(36, 0, "start", "/vanilla/tdata_allKd.stan");
    reader.add_event(39, 3, "end", "/vanilla/tdata_allKd.stan");
    reader.add_event(39, 36, "restart", "model_RR_con_comp_g1");
    reader.add_event(39, 36, "include", "/vanilla/tdata_allKp.stan");
    reader.add_event(39, 0, "start", "/vanilla/tdata_allKp.stan");
    reader.add_event(42, 3, "end", "/vanilla/tdata_allKp.stan");
    reader.add_event(42, 37, "restart", "model_RR_con_comp_g1");
    reader.add_event(45, 40, "include", "/means/means_parameters.stan");
    reader.add_event(45, 0, "start", "/means/means_parameters.stan");
    reader.add_event(46, 1, "end", "/means/means_parameters.stan");
    reader.add_event(46, 41, "restart", "model_RR_con_comp_g1");
    reader.add_event(118, 113, "include", "/vanilla/tpar_chol_p.stan");
    reader.add_event(118, 0, "start", "/vanilla/tpar_chol_p.stan");
    reader.add_event(119, 1, "end", "/vanilla/tpar_chol_p.stan");
    reader.add_event(119, 114, "restart", "model_RR_con_comp_g1");
    reader.add_event(134, 129, "include", "/means/means_tparameters.stan");
    reader.add_event(134, 0, "start", "/means/means_tparameters.stan");
    reader.add_event(140, 6, "end", "/means/means_tparameters.stan");
    reader.add_event(140, 130, "restart", "model_RR_con_comp_g1");
    reader.add_event(150, 140, "include", "/means/means_model.stan");
    reader.add_event(150, 0, "start", "/means/means_model.stan");
    reader.add_event(152, 2, "end", "/means/means_model.stan");
    reader.add_event(152, 141, "restart", "model_RR_con_comp_g1");
    reader.add_event(180, 169, "include", "/OneGroup/OneGroup_Rsq.stan");
    reader.add_event(180, 0, "start", "/OneGroup/OneGroup_Rsq.stan");
    reader.add_event(200, 20, "end", "/OneGroup/OneGroup_Rsq.stan");
    reader.add_event(200, 170, "restart", "model_RR_con_comp_g1");
    reader.add_event(208, 178, "include", "/include/license.stan");
    reader.add_event(208, 0, "start", "/include/license.stan");
    reader.add_event(222, 14, "end", "/include/license.stan");
    reader.add_event(222, 179, "restart", "model_RR_con_comp_g1");
    reader.add_event(224, 179, "end", "model_RR_con_comp_g1");
    return reader;
}
#include <stan_meta_header.hpp>
class model_RR_con_comp_g1
  : public stan::model::model_base_crtp<model_RR_con_comp_g1> {
private:
        int Nd;
        int Np;
        int Kd2;
        matrix_d Yd2;
        std::vector<std::vector<int> > IDp;
        vector_d rr_Mvec_m;
        vector_d rr_Mvec_sd;
        matrix_d rr_rel_t;
        matrix_d rr_out_t;
        matrix_d rr_in_t;
        double case_lkj;
        matrix_d rr_beta_a;
        matrix_d rr_beta_b;
        int allKd;
        int allKp;
public:
    model_RR_con_comp_g1(stan::io::var_context& context__,
        std::ostream* pstream__ = 0)
        : model_base_crtp(0) {
        ctor_body(context__, 0, pstream__);
    }
    model_RR_con_comp_g1(stan::io::var_context& context__,
        unsigned int random_seed__,
        std::ostream* pstream__ = 0)
        : model_base_crtp(0) {
        ctor_body(context__, random_seed__, pstream__);
    }
    void ctor_body(stan::io::var_context& context__,
                   unsigned int random_seed__,
                   std::ostream* pstream__) {
        typedef double local_scalar_t__;
        boost::ecuyer1988 base_rng__ =
          stan::services::util::create_rng(random_seed__, 0);
        (void) base_rng__;  // suppress unused var warning
        current_statement_begin__ = -1;
        static const char* function__ = "model_RR_con_comp_g1_namespace::model_RR_con_comp_g1";
        (void) function__;  // dummy to suppress unused var warning
        size_t pos__;
        (void) pos__;  // dummy to suppress unused var warning
        std::vector<int> vals_i__;
        std::vector<double> vals_r__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
        try {
            // initialize data block variables from context__
            current_statement_begin__ = 14;
            context__.validate_dims("data initialization", "Nd", "int", context__.to_vec());
            Nd = int(0);
            vals_i__ = context__.vals_i("Nd");
            pos__ = 0;
            Nd = vals_i__[pos__++];
            check_greater_or_equal(function__, "Nd", Nd, 0);
            current_statement_begin__ = 15;
            context__.validate_dims("data initialization", "Np", "int", context__.to_vec());
            Np = int(0);
            vals_i__ = context__.vals_i("Np");
            pos__ = 0;
            Np = vals_i__[pos__++];
            check_greater_or_equal(function__, "Np", Np, 0);
            current_statement_begin__ = 17;
            context__.validate_dims("data initialization", "Kd2", "int", context__.to_vec());
            Kd2 = int(0);
            vals_i__ = context__.vals_i("Kd2");
            pos__ = 0;
            Kd2 = vals_i__[pos__++];
            check_greater_or_equal(function__, "Kd2", Kd2, 0);
            current_statement_begin__ = 19;
            validate_non_negative_index("Yd2", "Nd", Nd);
            validate_non_negative_index("Yd2", "(2 * Kd2)", (2 * Kd2));
            context__.validate_dims("data initialization", "Yd2", "matrix_d", context__.to_vec(Nd,(2 * Kd2)));
            Yd2 = Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic>(Nd, (2 * Kd2));
            vals_r__ = context__.vals_r("Yd2");
            pos__ = 0;
            size_t Yd2_j_2_max__ = (2 * Kd2);
            size_t Yd2_j_1_max__ = Nd;
            for (size_t j_2__ = 0; j_2__ < Yd2_j_2_max__; ++j_2__) {
                for (size_t j_1__ = 0; j_1__ < Yd2_j_1_max__; ++j_1__) {
                    Yd2(j_1__, j_2__) = vals_r__[pos__++];
                }
            }
            current_statement_begin__ = 21;
            validate_non_negative_index("IDp", "Nd", Nd);
            validate_non_negative_index("IDp", "2", 2);
            context__.validate_dims("data initialization", "IDp", "int", context__.to_vec(Nd,2));
            IDp = std::vector<std::vector<int> >(Nd, std::vector<int>(2, int(0)));
            vals_i__ = context__.vals_i("IDp");
            pos__ = 0;
            size_t IDp_k_0_max__ = Nd;
            size_t IDp_k_1_max__ = 2;
            for (size_t k_1__ = 0; k_1__ < IDp_k_1_max__; ++k_1__) {
                for (size_t k_0__ = 0; k_0__ < IDp_k_0_max__; ++k_0__) {
                    IDp[k_0__][k_1__] = vals_i__[pos__++];
                }
            }
            current_statement_begin__ = 24;
            validate_non_negative_index("rr_Mvec_m", "Kd2", Kd2);
            context__.validate_dims("data initialization", "rr_Mvec_m", "vector_d", context__.to_vec(Kd2));
            rr_Mvec_m = Eigen::Matrix<double, Eigen::Dynamic, 1>(Kd2);
            vals_r__ = context__.vals_r("rr_Mvec_m");
            pos__ = 0;
            size_t rr_Mvec_m_j_1_max__ = Kd2;
            for (size_t j_1__ = 0; j_1__ < rr_Mvec_m_j_1_max__; ++j_1__) {
                rr_Mvec_m(j_1__) = vals_r__[pos__++];
            }
            current_statement_begin__ = 25;
            validate_non_negative_index("rr_Mvec_sd", "Kd2", Kd2);
            context__.validate_dims("data initialization", "rr_Mvec_sd", "vector_d", context__.to_vec(Kd2));
            rr_Mvec_sd = Eigen::Matrix<double, Eigen::Dynamic, 1>(Kd2);
            vals_r__ = context__.vals_r("rr_Mvec_sd");
            pos__ = 0;
            size_t rr_Mvec_sd_j_1_max__ = Kd2;
            for (size_t j_1__ = 0; j_1__ < rr_Mvec_sd_j_1_max__; ++j_1__) {
                rr_Mvec_sd(j_1__) = vals_r__[pos__++];
            }
            current_statement_begin__ = 27;
            validate_non_negative_index("rr_rel_t", "Kd2", Kd2);
            validate_non_negative_index("rr_rel_t", "3", 3);
            context__.validate_dims("data initialization", "rr_rel_t", "matrix_d", context__.to_vec(Kd2,3));
            rr_rel_t = Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic>(Kd2, 3);
            vals_r__ = context__.vals_r("rr_rel_t");
            pos__ = 0;
            size_t rr_rel_t_j_2_max__ = 3;
            size_t rr_rel_t_j_1_max__ = Kd2;
            for (size_t j_2__ = 0; j_2__ < rr_rel_t_j_2_max__; ++j_2__) {
                for (size_t j_1__ = 0; j_1__ < rr_rel_t_j_1_max__; ++j_1__) {
                    rr_rel_t(j_1__, j_2__) = vals_r__[pos__++];
                }
            }
            current_statement_begin__ = 28;
            validate_non_negative_index("rr_out_t", "Kd2", Kd2);
            validate_non_negative_index("rr_out_t", "3", 3);
            context__.validate_dims("data initialization", "rr_out_t", "matrix_d", context__.to_vec(Kd2,3));
            rr_out_t = Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic>(Kd2, 3);
            vals_r__ = context__.vals_r("rr_out_t");
            pos__ = 0;
            size_t rr_out_t_j_2_max__ = 3;
            size_t rr_out_t_j_1_max__ = Kd2;
            for (size_t j_2__ = 0; j_2__ < rr_out_t_j_2_max__; ++j_2__) {
                for (size_t j_1__ = 0; j_1__ < rr_out_t_j_1_max__; ++j_1__) {
                    rr_out_t(j_1__, j_2__) = vals_r__[pos__++];
                }
            }
            current_statement_begin__ = 29;
            validate_non_negative_index("rr_in_t", "Kd2", Kd2);
            validate_non_negative_index("rr_in_t", "3", 3);
            context__.validate_dims("data initialization", "rr_in_t", "matrix_d", context__.to_vec(Kd2,3));
            rr_in_t = Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic>(Kd2, 3);
            vals_r__ = context__.vals_r("rr_in_t");
            pos__ = 0;
            size_t rr_in_t_j_2_max__ = 3;
            size_t rr_in_t_j_1_max__ = Kd2;
            for (size_t j_2__ = 0; j_2__ < rr_in_t_j_2_max__; ++j_2__) {
                for (size_t j_1__ = 0; j_1__ < rr_in_t_j_1_max__; ++j_1__) {
                    rr_in_t(j_1__, j_2__) = vals_r__[pos__++];
                }
            }
            current_statement_begin__ = 31;
            context__.validate_dims("data initialization", "case_lkj", "double", context__.to_vec());
            case_lkj = double(0);
            vals_r__ = context__.vals_r("case_lkj");
            pos__ = 0;
            case_lkj = vals_r__[pos__++];
            current_statement_begin__ = 33;
            validate_non_negative_index("rr_beta_a", "Kd2", Kd2);
            validate_non_negative_index("rr_beta_a", "Kd2", Kd2);
            context__.validate_dims("data initialization", "rr_beta_a", "matrix_d", context__.to_vec(Kd2,Kd2));
            rr_beta_a = Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic>(Kd2, Kd2);
            vals_r__ = context__.vals_r("rr_beta_a");
            pos__ = 0;
            size_t rr_beta_a_j_2_max__ = Kd2;
            size_t rr_beta_a_j_1_max__ = Kd2;
            for (size_t j_2__ = 0; j_2__ < rr_beta_a_j_2_max__; ++j_2__) {
                for (size_t j_1__ = 0; j_1__ < rr_beta_a_j_1_max__; ++j_1__) {
                    rr_beta_a(j_1__, j_2__) = vals_r__[pos__++];
                }
            }
            current_statement_begin__ = 34;
            validate_non_negative_index("rr_beta_b", "Kd2", Kd2);
            validate_non_negative_index("rr_beta_b", "Kd2", Kd2);
            context__.validate_dims("data initialization", "rr_beta_b", "matrix_d", context__.to_vec(Kd2,Kd2));
            rr_beta_b = Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic>(Kd2, Kd2);
            vals_r__ = context__.vals_r("rr_beta_b");
            pos__ = 0;
            size_t rr_beta_b_j_2_max__ = Kd2;
            size_t rr_beta_b_j_1_max__ = Kd2;
            for (size_t j_2__ = 0; j_2__ < rr_beta_b_j_2_max__; ++j_2__) {
                for (size_t j_1__ = 0; j_1__ < rr_beta_b_j_1_max__; ++j_1__) {
                    rr_beta_b(j_1__, j_2__) = vals_r__[pos__++];
                }
            }
            // initialize transformed data variables
            current_statement_begin__ = 39;
            allKd = int(0);
            stan::math::fill(allKd, std::numeric_limits<int>::min());
            stan::math::assign(allKd,(2 * Kd2));
            current_statement_begin__ = 42;
            allKp = int(0);
            stan::math::fill(allKp, std::numeric_limits<int>::min());
            stan::math::assign(allKp,(2 * Kd2));
            // execute transformed data statements
            // validate transformed data
            // validate, set parameter ranges
            num_params_r__ = 0U;
            param_ranges_i__.clear();
            current_statement_begin__ = 46;
            validate_non_negative_index("Mvec", "Kd2", Kd2);
            num_params_r__ += Kd2;
            current_statement_begin__ = 49;
            validate_non_negative_index("s_rr", "Kd2", Kd2);
            num_params_r__ += Kd2;
            current_statement_begin__ = 50;
            validate_non_negative_index("S_p", "allKp", allKp);
            num_params_r__ += allKp;
            current_statement_begin__ = 53;
            validate_non_negative_index("chol_r_p", "allKp", allKp);
            validate_non_negative_index("chol_r_p", "allKp", allKp);
            num_params_r__ += ((allKp * (allKp - 1)) / 2);
            current_statement_begin__ = 58;
            validate_non_negative_index("r_d2", "Kd2", Kd2);
            validate_non_negative_index("r_d2", "Kd2", Kd2);
            num_params_r__ += (Kd2 * Kd2);
            current_statement_begin__ = 61;
            validate_non_negative_index("AP", "Np", Np);
            validate_non_negative_index("AP", "(2 * Kd2)", (2 * Kd2));
            num_params_r__ += (Np * (2 * Kd2));
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
    }
    ~model_RR_con_comp_g1() { }
    void transform_inits(const stan::io::var_context& context__,
                         std::vector<int>& params_i__,
                         std::vector<double>& params_r__,
                         std::ostream* pstream__) const {
        typedef double local_scalar_t__;
        stan::io::writer<double> writer__(params_r__, params_i__);
        size_t pos__;
        (void) pos__; // dummy call to supress warning
        std::vector<double> vals_r__;
        std::vector<int> vals_i__;
        current_statement_begin__ = 46;
        if (!(context__.contains_r("Mvec")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable Mvec missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("Mvec");
        pos__ = 0U;
        validate_non_negative_index("Mvec", "Kd2", Kd2);
        context__.validate_dims("parameter initialization", "Mvec", "vector_d", context__.to_vec(Kd2));
        Eigen::Matrix<double, Eigen::Dynamic, 1> Mvec(Kd2);
        size_t Mvec_j_1_max__ = Kd2;
        for (size_t j_1__ = 0; j_1__ < Mvec_j_1_max__; ++j_1__) {
            Mvec(j_1__) = vals_r__[pos__++];
        }
        try {
            writer__.vector_unconstrain(Mvec);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable Mvec: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 49;
        if (!(context__.contains_r("s_rr")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable s_rr missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("s_rr");
        pos__ = 0U;
        validate_non_negative_index("s_rr", "Kd2", Kd2);
        context__.validate_dims("parameter initialization", "s_rr", "vector_d", context__.to_vec(Kd2));
        Eigen::Matrix<double, Eigen::Dynamic, 1> s_rr(Kd2);
        size_t s_rr_j_1_max__ = Kd2;
        for (size_t j_1__ = 0; j_1__ < s_rr_j_1_max__; ++j_1__) {
            s_rr(j_1__) = vals_r__[pos__++];
        }
        try {
            writer__.vector_lb_unconstrain(0, s_rr);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable s_rr: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 50;
        if (!(context__.contains_r("S_p")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable S_p missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("S_p");
        pos__ = 0U;
        validate_non_negative_index("S_p", "allKp", allKp);
        context__.validate_dims("parameter initialization", "S_p", "vector_d", context__.to_vec(allKp));
        Eigen::Matrix<double, Eigen::Dynamic, 1> S_p(allKp);
        size_t S_p_j_1_max__ = allKp;
        for (size_t j_1__ = 0; j_1__ < S_p_j_1_max__; ++j_1__) {
            S_p(j_1__) = vals_r__[pos__++];
        }
        try {
            writer__.vector_lb_unconstrain(0, S_p);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable S_p: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 53;
        if (!(context__.contains_r("chol_r_p")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable chol_r_p missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("chol_r_p");
        pos__ = 0U;
        validate_non_negative_index("chol_r_p", "allKp", allKp);
        validate_non_negative_index("chol_r_p", "allKp", allKp);
        context__.validate_dims("parameter initialization", "chol_r_p", "matrix_d", context__.to_vec(allKp,allKp));
        Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic> chol_r_p(allKp, allKp);
        size_t chol_r_p_j_2_max__ = allKp;
        size_t chol_r_p_j_1_max__ = allKp;
        for (size_t j_2__ = 0; j_2__ < chol_r_p_j_2_max__; ++j_2__) {
            for (size_t j_1__ = 0; j_1__ < chol_r_p_j_1_max__; ++j_1__) {
                chol_r_p(j_1__, j_2__) = vals_r__[pos__++];
            }
        }
        try {
            writer__.cholesky_factor_corr_unconstrain(chol_r_p);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable chol_r_p: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 58;
        if (!(context__.contains_r("r_d2")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable r_d2 missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("r_d2");
        pos__ = 0U;
        validate_non_negative_index("r_d2", "Kd2", Kd2);
        validate_non_negative_index("r_d2", "Kd2", Kd2);
        context__.validate_dims("parameter initialization", "r_d2", "matrix_d", context__.to_vec(Kd2,Kd2));
        Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic> r_d2(Kd2, Kd2);
        size_t r_d2_j_2_max__ = Kd2;
        size_t r_d2_j_1_max__ = Kd2;
        for (size_t j_2__ = 0; j_2__ < r_d2_j_2_max__; ++j_2__) {
            for (size_t j_1__ = 0; j_1__ < r_d2_j_1_max__; ++j_1__) {
                r_d2(j_1__, j_2__) = vals_r__[pos__++];
            }
        }
        try {
            writer__.matrix_lub_unconstrain(0, 1, r_d2);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable r_d2: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 61;
        if (!(context__.contains_r("AP")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable AP missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("AP");
        pos__ = 0U;
        validate_non_negative_index("AP", "Np", Np);
        validate_non_negative_index("AP", "(2 * Kd2)", (2 * Kd2));
        context__.validate_dims("parameter initialization", "AP", "matrix_d", context__.to_vec(Np,(2 * Kd2)));
        Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic> AP(Np, (2 * Kd2));
        size_t AP_j_2_max__ = (2 * Kd2);
        size_t AP_j_1_max__ = Np;
        for (size_t j_2__ = 0; j_2__ < AP_j_2_max__; ++j_2__) {
            for (size_t j_1__ = 0; j_1__ < AP_j_1_max__; ++j_1__) {
                AP(j_1__, j_2__) = vals_r__[pos__++];
            }
        }
        try {
            writer__.matrix_unconstrain(AP);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable AP: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        params_r__ = writer__.data_r();
        params_i__ = writer__.data_i();
    }
    void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream__) const {
      std::vector<double> params_r_vec;
      std::vector<int> params_i_vec;
      transform_inits(context, params_i_vec, params_r_vec, pstream__);
      params_r.resize(params_r_vec.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r(i) = params_r_vec[i];
    }
    template <bool propto__, bool jacobian__, typename T__>
    T__ log_prob(std::vector<T__>& params_r__,
                 std::vector<int>& params_i__,
                 std::ostream* pstream__ = 0) const {
        typedef T__ local_scalar_t__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // dummy to suppress unused var warning
        T__ lp__(0.0);
        stan::math::accumulator<T__> lp_accum__;
        try {
            stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
            // model parameters
            current_statement_begin__ = 46;
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> Mvec;
            (void) Mvec;  // dummy to suppress unused var warning
            if (jacobian__)
                Mvec = in__.vector_constrain(Kd2, lp__);
            else
                Mvec = in__.vector_constrain(Kd2);
            current_statement_begin__ = 49;
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> s_rr;
            (void) s_rr;  // dummy to suppress unused var warning
            if (jacobian__)
                s_rr = in__.vector_lb_constrain(0, Kd2, lp__);
            else
                s_rr = in__.vector_lb_constrain(0, Kd2);
            current_statement_begin__ = 50;
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> S_p;
            (void) S_p;  // dummy to suppress unused var warning
            if (jacobian__)
                S_p = in__.vector_lb_constrain(0, allKp, lp__);
            else
                S_p = in__.vector_lb_constrain(0, allKp);
            current_statement_begin__ = 53;
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, Eigen::Dynamic> chol_r_p;
            (void) chol_r_p;  // dummy to suppress unused var warning
            if (jacobian__)
                chol_r_p = in__.cholesky_factor_corr_constrain(allKp, lp__);
            else
                chol_r_p = in__.cholesky_factor_corr_constrain(allKp);
            current_statement_begin__ = 58;
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, Eigen::Dynamic> r_d2;
            (void) r_d2;  // dummy to suppress unused var warning
            if (jacobian__)
                r_d2 = in__.matrix_lub_constrain(0, 1, Kd2, Kd2, lp__);
            else
                r_d2 = in__.matrix_lub_constrain(0, 1, Kd2, Kd2);
            current_statement_begin__ = 61;
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, Eigen::Dynamic> AP;
            (void) AP;  // dummy to suppress unused var warning
            if (jacobian__)
                AP = in__.matrix_constrain(Np, (2 * Kd2), lp__);
            else
                AP = in__.matrix_constrain(Np, (2 * Kd2));
            // transformed parameters
            current_statement_begin__ = 65;
            validate_non_negative_index("Yd2hat", "Nd", Nd);
            validate_non_negative_index("Yd2hat", "allKd", allKd);
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, Eigen::Dynamic> Yd2hat(Nd, allKd);
            stan::math::initialize(Yd2hat, DUMMY_VAR__);
            stan::math::fill(Yd2hat, DUMMY_VAR__);
            current_statement_begin__ = 67;
            validate_non_negative_index("S_d", "allKd", allKd);
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> S_d(allKd);
            stan::math::initialize(S_d, DUMMY_VAR__);
            stan::math::fill(S_d, DUMMY_VAR__);
            current_statement_begin__ = 68;
            validate_non_negative_index("Rd2", "allKd", allKd);
            validate_non_negative_index("Rd2", "allKd", allKd);
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, Eigen::Dynamic> Rd2(allKd, allKd);
            stan::math::initialize(Rd2, DUMMY_VAR__);
            stan::math::fill(Rd2, DUMMY_VAR__);
            current_statement_begin__ = 70;
            validate_non_negative_index("chol_d", "allKd", allKd);
            validate_non_negative_index("chol_d", "allKd", allKd);
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, Eigen::Dynamic> chol_d(allKd, allKd);
            stan::math::initialize(chol_d, DUMMY_VAR__);
            stan::math::fill(chol_d, DUMMY_VAR__);
            current_statement_begin__ = 71;
            validate_non_negative_index("chol_p", "allKp", allKp);
            validate_non_negative_index("chol_p", "allKp", allKp);
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, Eigen::Dynamic> chol_p(allKp, allKp);
            stan::math::initialize(chol_p, DUMMY_VAR__);
            stan::math::fill(chol_p, DUMMY_VAR__);
            current_statement_begin__ = 75;
            validate_non_negative_index("augYd", "Nd", Nd);
            validate_non_negative_index("augYd", "allKd", allKd);
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, Eigen::Dynamic> augYd(Nd, allKd);
            stan::math::initialize(augYd, DUMMY_VAR__);
            stan::math::fill(augYd, DUMMY_VAR__);
            current_statement_begin__ = 76;
            validate_non_negative_index("augYp", "Np", Np);
            validate_non_negative_index("augYp", "allKp", allKp);
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, Eigen::Dynamic> augYp(Np, allKp);
            stan::math::initialize(augYp, DUMMY_VAR__);
            stan::math::fill(augYp, DUMMY_VAR__);
            // transformed parameters block statements
            {
            current_statement_begin__ = 80;
            int idx1(0);
            (void) idx1;  // dummy to suppress unused var warning
            stan::math::fill(idx1, std::numeric_limits<int>::min());
            current_statement_begin__ = 81;
            int idx2(0);
            (void) idx2;  // dummy to suppress unused var warning
            stan::math::fill(idx2, std::numeric_limits<int>::min());
            current_statement_begin__ = 82;
            int idp1(0);
            (void) idp1;  // dummy to suppress unused var warning
            stan::math::fill(idp1, std::numeric_limits<int>::min());
            current_statement_begin__ = 83;
            int idp2(0);
            (void) idp2;  // dummy to suppress unused var warning
            stan::math::fill(idp2, std::numeric_limits<int>::min());
            current_statement_begin__ = 85;
            for (int k = 1; k <= Kd2; ++k) {
                current_statement_begin__ = 86;
                stan::math::assign(idx1, ((k * 2) - 1));
                current_statement_begin__ = 87;
                stan::math::assign(idx2, (k * 2));
                current_statement_begin__ = 90;
                stan::model::assign(S_d, 
                            stan::model::cons_list(stan::model::index_uni(idx1), stan::model::nil_index_list()), 
                            get_base1(s_rr, k, "s_rr", 1), 
                            "assigning variable S_d");
                current_statement_begin__ = 91;
                stan::model::assign(S_d, 
                            stan::model::cons_list(stan::model::index_uni(idx2), stan::model::nil_index_list()), 
                            get_base1(s_rr, k, "s_rr", 1), 
                            "assigning variable S_d");
                current_statement_begin__ = 92;
                stan::model::assign(Rd2, 
                            stan::model::cons_list(stan::model::index_uni(idx1), stan::model::cons_list(stan::model::index_uni(idx1), stan::model::nil_index_list())), 
                            1, 
                            "assigning variable Rd2");
                current_statement_begin__ = 93;
                stan::model::assign(Rd2, 
                            stan::model::cons_list(stan::model::index_uni(idx2), stan::model::cons_list(stan::model::index_uni(idx2), stan::model::nil_index_list())), 
                            1, 
                            "assigning variable Rd2");
                current_statement_begin__ = 94;
                stan::model::assign(Rd2, 
                            stan::model::cons_list(stan::model::index_uni(idx1), stan::model::cons_list(stan::model::index_uni(idx2), stan::model::nil_index_list())), 
                            (-(1) + (2 * get_base1(r_d2, k, k, "r_d2", 1))), 
                            "assigning variable Rd2");
                current_statement_begin__ = 95;
                stan::model::assign(Rd2, 
                            stan::model::cons_list(stan::model::index_uni(idx2), stan::model::cons_list(stan::model::index_uni(idx1), stan::model::nil_index_list())), 
                            (-(1) + (2 * get_base1(r_d2, k, k, "r_d2", 1))), 
                            "assigning variable Rd2");
                current_statement_begin__ = 98;
                if (as_bool(logical_lt(k, Kd2))) {
                    current_statement_begin__ = 98;
                    for (int kk = (k + 1); kk <= Kd2; ++kk) {
                        current_statement_begin__ = 99;
                        stan::math::assign(idp1, ((kk * 2) - 1));
                        current_statement_begin__ = 100;
                        stan::math::assign(idp2, (kk * 2));
                        current_statement_begin__ = 102;
                        stan::model::assign(Rd2, 
                                    stan::model::cons_list(stan::model::index_uni(idx1), stan::model::cons_list(stan::model::index_uni(idp1), stan::model::nil_index_list())), 
                                    (-(1) + (2 * get_base1(r_d2, kk, k, "r_d2", 1))), 
                                    "assigning variable Rd2");
                        current_statement_begin__ = 103;
                        stan::model::assign(Rd2, 
                                    stan::model::cons_list(stan::model::index_uni(idx2), stan::model::cons_list(stan::model::index_uni(idp2), stan::model::nil_index_list())), 
                                    (-(1) + (2 * get_base1(r_d2, kk, k, "r_d2", 1))), 
                                    "assigning variable Rd2");
                        current_statement_begin__ = 104;
                        stan::model::assign(Rd2, 
                                    stan::model::cons_list(stan::model::index_uni(idp1), stan::model::cons_list(stan::model::index_uni(idx1), stan::model::nil_index_list())), 
                                    (-(1) + (2 * get_base1(r_d2, kk, k, "r_d2", 1))), 
                                    "assigning variable Rd2");
                        current_statement_begin__ = 105;
                        stan::model::assign(Rd2, 
                                    stan::model::cons_list(stan::model::index_uni(idp2), stan::model::cons_list(stan::model::index_uni(idx2), stan::model::nil_index_list())), 
                                    (-(1) + (2 * get_base1(r_d2, kk, k, "r_d2", 1))), 
                                    "assigning variable Rd2");
                        current_statement_begin__ = 106;
                        stan::model::assign(Rd2, 
                                    stan::model::cons_list(stan::model::index_uni(idx1), stan::model::cons_list(stan::model::index_uni(idp2), stan::model::nil_index_list())), 
                                    (-(1) + (2 * get_base1(r_d2, k, kk, "r_d2", 1))), 
                                    "assigning variable Rd2");
                        current_statement_begin__ = 107;
                        stan::model::assign(Rd2, 
                                    stan::model::cons_list(stan::model::index_uni(idp2), stan::model::cons_list(stan::model::index_uni(idx1), stan::model::nil_index_list())), 
                                    (-(1) + (2 * get_base1(r_d2, k, kk, "r_d2", 1))), 
                                    "assigning variable Rd2");
                        current_statement_begin__ = 108;
                        stan::model::assign(Rd2, 
                                    stan::model::cons_list(stan::model::index_uni(idx2), stan::model::cons_list(stan::model::index_uni(idp1), stan::model::nil_index_list())), 
                                    (-(1) + (2 * get_base1(r_d2, k, kk, "r_d2", 1))), 
                                    "assigning variable Rd2");
                        current_statement_begin__ = 109;
                        stan::model::assign(Rd2, 
                                    stan::model::cons_list(stan::model::index_uni(idp1), stan::model::cons_list(stan::model::index_uni(idx2), stan::model::nil_index_list())), 
                                    (-(1) + (2 * get_base1(r_d2, k, kk, "r_d2", 1))), 
                                    "assigning variable Rd2");
                    }
                }
            }
            }
            current_statement_begin__ = 117;
            stan::math::assign(chol_d, diag_pre_multiply(S_d, cholesky_decompose(Rd2)));
            current_statement_begin__ = 119;
            stan::math::assign(chol_p, chol_r_p);
            {
            current_statement_begin__ = 123;
            int idx1(0);
            (void) idx1;  // dummy to suppress unused var warning
            stan::math::fill(idx1, std::numeric_limits<int>::min());
            current_statement_begin__ = 124;
            int idx2(0);
            (void) idx2;  // dummy to suppress unused var warning
            stan::math::fill(idx2, std::numeric_limits<int>::min());
            current_statement_begin__ = 126;
            for (int k = 1; k <= Kd2; ++k) {
                current_statement_begin__ = 127;
                stan::math::assign(idx1, ((k * 2) - 1));
                current_statement_begin__ = 128;
                stan::math::assign(idx2, (k * 2));
                current_statement_begin__ = 130;
                for (int d = 1; d <= Nd; ++d) {
                    current_statement_begin__ = 132;
                    stan::model::assign(Yd2hat, 
                                stan::model::cons_list(stan::model::index_uni(d), stan::model::cons_list(stan::model::index_uni(idx1), stan::model::nil_index_list())), 
                                ((get_base1(S_p, idx1, "S_p", 1) * get_base1(AP, get_base1(get_base1(IDp, d, "IDp", 1), 1, "IDp", 2), idx1, "AP", 1)) + (get_base1(S_p, idx2, "S_p", 1) * get_base1(AP, get_base1(get_base1(IDp, d, "IDp", 1), 2, "IDp", 2), idx2, "AP", 1))), 
                                "assigning variable Yd2hat");
                    current_statement_begin__ = 133;
                    stan::model::assign(Yd2hat, 
                                stan::model::cons_list(stan::model::index_uni(d), stan::model::cons_list(stan::model::index_uni(idx2), stan::model::nil_index_list())), 
                                ((get_base1(S_p, idx1, "S_p", 1) * get_base1(AP, get_base1(get_base1(IDp, d, "IDp", 1), 2, "IDp", 2), idx1, "AP", 1)) + (get_base1(S_p, idx2, "S_p", 1) * get_base1(AP, get_base1(get_base1(IDp, d, "IDp", 1), 1, "IDp", 2), idx2, "AP", 1))), 
                                "assigning variable Yd2hat");
                    current_statement_begin__ = 139;
                    stan::model::assign(augYd, 
                                stan::model::cons_list(stan::model::index_uni(d), stan::model::cons_list(stan::model::index_uni(idx1), stan::model::nil_index_list())), 
                                (stan::model::rvalue(augYd, stan::model::cons_list(stan::model::index_uni(d), stan::model::cons_list(stan::model::index_uni(idx1), stan::model::nil_index_list())), "augYd") + get_base1(Mvec, k, "Mvec", 1)), 
                                "assigning variable augYd");
                    current_statement_begin__ = 140;
                    stan::model::assign(augYd, 
                                stan::model::cons_list(stan::model::index_uni(d), stan::model::cons_list(stan::model::index_uni(idx2), stan::model::nil_index_list())), 
                                (stan::model::rvalue(augYd, stan::model::cons_list(stan::model::index_uni(d), stan::model::cons_list(stan::model::index_uni(idx2), stan::model::nil_index_list())), "augYd") + get_base1(Mvec, k, "Mvec", 1)), 
                                "assigning variable augYd");
                }
            }
            }
            // validate transformed parameters
            const char* function__ = "validate transformed params";
            (void) function__;  // dummy to suppress unused var warning
            current_statement_begin__ = 65;
            size_t Yd2hat_j_1_max__ = Nd;
            size_t Yd2hat_j_2_max__ = allKd;
            for (size_t j_1__ = 0; j_1__ < Yd2hat_j_1_max__; ++j_1__) {
                for (size_t j_2__ = 0; j_2__ < Yd2hat_j_2_max__; ++j_2__) {
                    if (stan::math::is_uninitialized(Yd2hat(j_1__, j_2__))) {
                        std::stringstream msg__;
                        msg__ << "Undefined transformed parameter: Yd2hat" << "(" << j_1__ << ", " << j_2__ << ")";
                        stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable Yd2hat: ") + msg__.str()), current_statement_begin__, prog_reader__());
                    }
                }
            }
            current_statement_begin__ = 67;
            size_t S_d_j_1_max__ = allKd;
            for (size_t j_1__ = 0; j_1__ < S_d_j_1_max__; ++j_1__) {
                if (stan::math::is_uninitialized(S_d(j_1__))) {
                    std::stringstream msg__;
                    msg__ << "Undefined transformed parameter: S_d" << "(" << j_1__ << ")";
                    stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable S_d: ") + msg__.str()), current_statement_begin__, prog_reader__());
                }
            }
            current_statement_begin__ = 68;
            size_t Rd2_j_1_max__ = allKd;
            size_t Rd2_j_2_max__ = allKd;
            for (size_t j_1__ = 0; j_1__ < Rd2_j_1_max__; ++j_1__) {
                for (size_t j_2__ = 0; j_2__ < Rd2_j_2_max__; ++j_2__) {
                    if (stan::math::is_uninitialized(Rd2(j_1__, j_2__))) {
                        std::stringstream msg__;
                        msg__ << "Undefined transformed parameter: Rd2" << "(" << j_1__ << ", " << j_2__ << ")";
                        stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable Rd2: ") + msg__.str()), current_statement_begin__, prog_reader__());
                    }
                }
            }
            current_statement_begin__ = 70;
            size_t chol_d_j_1_max__ = allKd;
            size_t chol_d_j_2_max__ = allKd;
            for (size_t j_1__ = 0; j_1__ < chol_d_j_1_max__; ++j_1__) {
                for (size_t j_2__ = 0; j_2__ < chol_d_j_2_max__; ++j_2__) {
                    if (stan::math::is_uninitialized(chol_d(j_1__, j_2__))) {
                        std::stringstream msg__;
                        msg__ << "Undefined transformed parameter: chol_d" << "(" << j_1__ << ", " << j_2__ << ")";
                        stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable chol_d: ") + msg__.str()), current_statement_begin__, prog_reader__());
                    }
                }
            }
            current_statement_begin__ = 71;
            size_t chol_p_j_1_max__ = allKp;
            size_t chol_p_j_2_max__ = allKp;
            for (size_t j_1__ = 0; j_1__ < chol_p_j_1_max__; ++j_1__) {
                for (size_t j_2__ = 0; j_2__ < chol_p_j_2_max__; ++j_2__) {
                    if (stan::math::is_uninitialized(chol_p(j_1__, j_2__))) {
                        std::stringstream msg__;
                        msg__ << "Undefined transformed parameter: chol_p" << "(" << j_1__ << ", " << j_2__ << ")";
                        stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable chol_p: ") + msg__.str()), current_statement_begin__, prog_reader__());
                    }
                }
            }
            current_statement_begin__ = 75;
            size_t augYd_j_1_max__ = Nd;
            size_t augYd_j_2_max__ = allKd;
            for (size_t j_1__ = 0; j_1__ < augYd_j_1_max__; ++j_1__) {
                for (size_t j_2__ = 0; j_2__ < augYd_j_2_max__; ++j_2__) {
                    if (stan::math::is_uninitialized(augYd(j_1__, j_2__))) {
                        std::stringstream msg__;
                        msg__ << "Undefined transformed parameter: augYd" << "(" << j_1__ << ", " << j_2__ << ")";
                        stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable augYd: ") + msg__.str()), current_statement_begin__, prog_reader__());
                    }
                }
            }
            current_statement_begin__ = 76;
            size_t augYp_j_1_max__ = Np;
            size_t augYp_j_2_max__ = allKp;
            for (size_t j_1__ = 0; j_1__ < augYp_j_1_max__; ++j_1__) {
                for (size_t j_2__ = 0; j_2__ < augYp_j_2_max__; ++j_2__) {
                    if (stan::math::is_uninitialized(augYp(j_1__, j_2__))) {
                        std::stringstream msg__;
                        msg__ << "Undefined transformed parameter: augYp" << "(" << j_1__ << ", " << j_2__ << ")";
                        stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable augYp: ") + msg__.str()), current_statement_begin__, prog_reader__());
                    }
                }
            }
            // model body
            current_statement_begin__ = 149;
            for (int k = 1; k <= Kd2; ++k) {
                current_statement_begin__ = 152;
                lp_accum__.add(normal_log<propto__>(get_base1(Mvec, k, "Mvec", 1), rr_Mvec_m, rr_Mvec_sd));
                current_statement_begin__ = 154;
                lp_accum__.add(student_t_log<propto__>(get_base1(s_rr, k, "s_rr", 1), get_base1(rr_rel_t, k, 1, "rr_rel_t", 1), get_base1(rr_rel_t, k, 2, "rr_rel_t", 1), get_base1(rr_rel_t, k, 3, "rr_rel_t", 1)));
                if (get_base1(s_rr, k, "s_rr", 1) < 0) lp_accum__.add(-std::numeric_limits<double>::infinity());
                else lp_accum__.add(-student_t_ccdf_log(0, get_base1(rr_rel_t, k, 1, "rr_rel_t", 1), get_base1(rr_rel_t, k, 2, "rr_rel_t", 1), get_base1(rr_rel_t, k, 3, "rr_rel_t", 1)));
                current_statement_begin__ = 156;
                lp_accum__.add(student_t_log<propto__>(get_base1(S_p, ((2 * k) - 1), "S_p", 1), get_base1(rr_out_t, k, 1, "rr_out_t", 1), get_base1(rr_out_t, k, 2, "rr_out_t", 1), get_base1(rr_out_t, k, 3, "rr_out_t", 1)));
                if (get_base1(S_p, ((2 * k) - 1), "S_p", 1) < 0) lp_accum__.add(-std::numeric_limits<double>::infinity());
                else lp_accum__.add(-student_t_ccdf_log(0, get_base1(rr_out_t, k, 1, "rr_out_t", 1), get_base1(rr_out_t, k, 2, "rr_out_t", 1), get_base1(rr_out_t, k, 3, "rr_out_t", 1)));
                current_statement_begin__ = 158;
                lp_accum__.add(student_t_log<propto__>(get_base1(S_p, (2 * k), "S_p", 1), get_base1(rr_in_t, k, 1, "rr_in_t", 1), get_base1(rr_in_t, k, 2, "rr_in_t", 1), get_base1(rr_in_t, k, 3, "rr_in_t", 1)));
                if (get_base1(S_p, (2 * k), "S_p", 1) < 0) lp_accum__.add(-std::numeric_limits<double>::infinity());
                else lp_accum__.add(-student_t_ccdf_log(0, get_base1(rr_in_t, k, 1, "rr_in_t", 1), get_base1(rr_in_t, k, 2, "rr_in_t", 1), get_base1(rr_in_t, k, 3, "rr_in_t", 1)));
            }
            current_statement_begin__ = 162;
            lp_accum__.add(lkj_corr_cholesky_log<propto__>(chol_r_p, case_lkj));
            current_statement_begin__ = 163;
            for (int k = 1; k <= Kd2; ++k) {
                current_statement_begin__ = 165;
                lp_accum__.add(beta_log<propto__>(get_base1(r_d2, k, k, "r_d2", 1), get_base1(rr_beta_a, k, k, "rr_beta_a", 1), get_base1(rr_beta_b, k, k, "rr_beta_b", 1)));
                current_statement_begin__ = 167;
                if (as_bool(logical_lt(k, Kd2))) {
                    current_statement_begin__ = 167;
                    for (int kk = (k + 1); kk <= Kd2; ++kk) {
                        current_statement_begin__ = 168;
                        lp_accum__.add(beta_log<propto__>(get_base1(r_d2, kk, k, "r_d2", 1), get_base1(rr_beta_a, kk, k, "rr_beta_a", 1), get_base1(rr_beta_b, kk, k, "rr_beta_b", 1)));
                        current_statement_begin__ = 169;
                        lp_accum__.add(beta_log<propto__>(get_base1(r_d2, k, kk, "r_d2", 1), get_base1(rr_beta_a, k, kk, "rr_beta_a", 1), get_base1(rr_beta_b, k, kk, "rr_beta_b", 1)));
                    }
                }
            }
            current_statement_begin__ = 174;
            for (int n = 1; n <= Nd; ++n) {
                current_statement_begin__ = 174;
                lp_accum__.add(multi_normal_cholesky_log<propto__>(stan::model::rvalue(augYd, stan::model::cons_list(stan::model::index_uni(n), stan::model::cons_list(stan::model::index_omni(), stan::model::nil_index_list())), "augYd"), stan::model::rvalue(Yd2hat, stan::model::cons_list(stan::model::index_uni(n), stan::model::cons_list(stan::model::index_omni(), stan::model::nil_index_list())), "Yd2hat"), chol_d));
            }
            current_statement_begin__ = 175;
            for (int n = 1; n <= Np; ++n) {
                current_statement_begin__ = 175;
                lp_accum__.add(multi_normal_cholesky_log<propto__>(stan::model::rvalue(augYp, stan::model::cons_list(stan::model::index_uni(n), stan::model::cons_list(stan::model::index_omni(), stan::model::nil_index_list())), "augYp"), rep_row_vector(0, allKp), chol_p));
            }
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
        lp_accum__.add(lp__);
        return lp_accum__.sum();
    } // log_prob()
    template <bool propto, bool jacobian, typename T_>
    T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
               std::ostream* pstream = 0) const {
      std::vector<T_> vec_params_r;
      vec_params_r.reserve(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        vec_params_r.push_back(params_r(i));
      std::vector<int> vec_params_i;
      return log_prob<propto,jacobian,T_>(vec_params_r, vec_params_i, pstream);
    }
    void get_param_names(std::vector<std::string>& names__) const {
        names__.resize(0);
        names__.push_back("Mvec");
        names__.push_back("s_rr");
        names__.push_back("S_p");
        names__.push_back("chol_r_p");
        names__.push_back("r_d2");
        names__.push_back("AP");
        names__.push_back("Yd2hat");
        names__.push_back("S_d");
        names__.push_back("Rd2");
        names__.push_back("chol_d");
        names__.push_back("chol_p");
        names__.push_back("augYd");
        names__.push_back("augYp");
        names__.push_back("Yd2e");
        names__.push_back("Rp");
        names__.push_back("Rsq");
    }
    void get_dims(std::vector<std::vector<size_t> >& dimss__) const {
        dimss__.resize(0);
        std::vector<size_t> dims__;
        dims__.resize(0);
        dims__.push_back(Kd2);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(Kd2);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(allKp);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(allKp);
        dims__.push_back(allKp);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(Kd2);
        dims__.push_back(Kd2);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(Np);
        dims__.push_back((2 * Kd2));
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(Nd);
        dims__.push_back(allKd);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(allKd);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(allKd);
        dims__.push_back(allKd);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(allKd);
        dims__.push_back(allKd);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(allKp);
        dims__.push_back(allKp);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(Nd);
        dims__.push_back(allKd);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(Np);
        dims__.push_back(allKp);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(Nd);
        dims__.push_back(allKd);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(allKp);
        dims__.push_back(allKp);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(Kd2);
        dims__.push_back(3);
        dimss__.push_back(dims__);
    }
    template <typename RNG>
    void write_array(RNG& base_rng__,
                     std::vector<double>& params_r__,
                     std::vector<int>& params_i__,
                     std::vector<double>& vars__,
                     bool include_tparams__ = true,
                     bool include_gqs__ = true,
                     std::ostream* pstream__ = 0) const {
        typedef double local_scalar_t__;
        vars__.resize(0);
        stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
        static const char* function__ = "model_RR_con_comp_g1_namespace::write_array";
        (void) function__;  // dummy to suppress unused var warning
        // read-transform, write parameters
        Eigen::Matrix<double, Eigen::Dynamic, 1> Mvec = in__.vector_constrain(Kd2);
        size_t Mvec_j_1_max__ = Kd2;
        for (size_t j_1__ = 0; j_1__ < Mvec_j_1_max__; ++j_1__) {
            vars__.push_back(Mvec(j_1__));
        }
        Eigen::Matrix<double, Eigen::Dynamic, 1> s_rr = in__.vector_lb_constrain(0, Kd2);
        size_t s_rr_j_1_max__ = Kd2;
        for (size_t j_1__ = 0; j_1__ < s_rr_j_1_max__; ++j_1__) {
            vars__.push_back(s_rr(j_1__));
        }
        Eigen::Matrix<double, Eigen::Dynamic, 1> S_p = in__.vector_lb_constrain(0, allKp);
        size_t S_p_j_1_max__ = allKp;
        for (size_t j_1__ = 0; j_1__ < S_p_j_1_max__; ++j_1__) {
            vars__.push_back(S_p(j_1__));
        }
        Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic> chol_r_p = in__.cholesky_factor_corr_constrain(allKp);
        size_t chol_r_p_j_2_max__ = allKp;
        size_t chol_r_p_j_1_max__ = allKp;
        for (size_t j_2__ = 0; j_2__ < chol_r_p_j_2_max__; ++j_2__) {
            for (size_t j_1__ = 0; j_1__ < chol_r_p_j_1_max__; ++j_1__) {
                vars__.push_back(chol_r_p(j_1__, j_2__));
            }
        }
        Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic> r_d2 = in__.matrix_lub_constrain(0, 1, Kd2, Kd2);
        size_t r_d2_j_2_max__ = Kd2;
        size_t r_d2_j_1_max__ = Kd2;
        for (size_t j_2__ = 0; j_2__ < r_d2_j_2_max__; ++j_2__) {
            for (size_t j_1__ = 0; j_1__ < r_d2_j_1_max__; ++j_1__) {
                vars__.push_back(r_d2(j_1__, j_2__));
            }
        }
        Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic> AP = in__.matrix_constrain(Np, (2 * Kd2));
        size_t AP_j_2_max__ = (2 * Kd2);
        size_t AP_j_1_max__ = Np;
        for (size_t j_2__ = 0; j_2__ < AP_j_2_max__; ++j_2__) {
            for (size_t j_1__ = 0; j_1__ < AP_j_1_max__; ++j_1__) {
                vars__.push_back(AP(j_1__, j_2__));
            }
        }
        double lp__ = 0.0;
        (void) lp__;  // dummy to suppress unused var warning
        stan::math::accumulator<double> lp_accum__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
        if (!include_tparams__ && !include_gqs__) return;
        try {
            // declare and define transformed parameters
            current_statement_begin__ = 65;
            validate_non_negative_index("Yd2hat", "Nd", Nd);
            validate_non_negative_index("Yd2hat", "allKd", allKd);
            Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic> Yd2hat(Nd, allKd);
            stan::math::initialize(Yd2hat, DUMMY_VAR__);
            stan::math::fill(Yd2hat, DUMMY_VAR__);
            current_statement_begin__ = 67;
            validate_non_negative_index("S_d", "allKd", allKd);
            Eigen::Matrix<double, Eigen::Dynamic, 1> S_d(allKd);
            stan::math::initialize(S_d, DUMMY_VAR__);
            stan::math::fill(S_d, DUMMY_VAR__);
            current_statement_begin__ = 68;
            validate_non_negative_index("Rd2", "allKd", allKd);
            validate_non_negative_index("Rd2", "allKd", allKd);
            Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic> Rd2(allKd, allKd);
            stan::math::initialize(Rd2, DUMMY_VAR__);
            stan::math::fill(Rd2, DUMMY_VAR__);
            current_statement_begin__ = 70;
            validate_non_negative_index("chol_d", "allKd", allKd);
            validate_non_negative_index("chol_d", "allKd", allKd);
            Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic> chol_d(allKd, allKd);
            stan::math::initialize(chol_d, DUMMY_VAR__);
            stan::math::fill(chol_d, DUMMY_VAR__);
            current_statement_begin__ = 71;
            validate_non_negative_index("chol_p", "allKp", allKp);
            validate_non_negative_index("chol_p", "allKp", allKp);
            Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic> chol_p(allKp, allKp);
            stan::math::initialize(chol_p, DUMMY_VAR__);
            stan::math::fill(chol_p, DUMMY_VAR__);
            current_statement_begin__ = 75;
            validate_non_negative_index("augYd", "Nd", Nd);
            validate_non_negative_index("augYd", "allKd", allKd);
            Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic> augYd(Nd, allKd);
            stan::math::initialize(augYd, DUMMY_VAR__);
            stan::math::fill(augYd, DUMMY_VAR__);
            current_statement_begin__ = 76;
            validate_non_negative_index("augYp", "Np", Np);
            validate_non_negative_index("augYp", "allKp", allKp);
            Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic> augYp(Np, allKp);
            stan::math::initialize(augYp, DUMMY_VAR__);
            stan::math::fill(augYp, DUMMY_VAR__);
            // do transformed parameters statements
            {
            current_statement_begin__ = 80;
            int idx1(0);
            (void) idx1;  // dummy to suppress unused var warning
            stan::math::fill(idx1, std::numeric_limits<int>::min());
            current_statement_begin__ = 81;
            int idx2(0);
            (void) idx2;  // dummy to suppress unused var warning
            stan::math::fill(idx2, std::numeric_limits<int>::min());
            current_statement_begin__ = 82;
            int idp1(0);
            (void) idp1;  // dummy to suppress unused var warning
            stan::math::fill(idp1, std::numeric_limits<int>::min());
            current_statement_begin__ = 83;
            int idp2(0);
            (void) idp2;  // dummy to suppress unused var warning
            stan::math::fill(idp2, std::numeric_limits<int>::min());
            current_statement_begin__ = 85;
            for (int k = 1; k <= Kd2; ++k) {
                current_statement_begin__ = 86;
                stan::math::assign(idx1, ((k * 2) - 1));
                current_statement_begin__ = 87;
                stan::math::assign(idx2, (k * 2));
                current_statement_begin__ = 90;
                stan::model::assign(S_d, 
                            stan::model::cons_list(stan::model::index_uni(idx1), stan::model::nil_index_list()), 
                            get_base1(s_rr, k, "s_rr", 1), 
                            "assigning variable S_d");
                current_statement_begin__ = 91;
                stan::model::assign(S_d, 
                            stan::model::cons_list(stan::model::index_uni(idx2), stan::model::nil_index_list()), 
                            get_base1(s_rr, k, "s_rr", 1), 
                            "assigning variable S_d");
                current_statement_begin__ = 92;
                stan::model::assign(Rd2, 
                            stan::model::cons_list(stan::model::index_uni(idx1), stan::model::cons_list(stan::model::index_uni(idx1), stan::model::nil_index_list())), 
                            1, 
                            "assigning variable Rd2");
                current_statement_begin__ = 93;
                stan::model::assign(Rd2, 
                            stan::model::cons_list(stan::model::index_uni(idx2), stan::model::cons_list(stan::model::index_uni(idx2), stan::model::nil_index_list())), 
                            1, 
                            "assigning variable Rd2");
                current_statement_begin__ = 94;
                stan::model::assign(Rd2, 
                            stan::model::cons_list(stan::model::index_uni(idx1), stan::model::cons_list(stan::model::index_uni(idx2), stan::model::nil_index_list())), 
                            (-(1) + (2 * get_base1(r_d2, k, k, "r_d2", 1))), 
                            "assigning variable Rd2");
                current_statement_begin__ = 95;
                stan::model::assign(Rd2, 
                            stan::model::cons_list(stan::model::index_uni(idx2), stan::model::cons_list(stan::model::index_uni(idx1), stan::model::nil_index_list())), 
                            (-(1) + (2 * get_base1(r_d2, k, k, "r_d2", 1))), 
                            "assigning variable Rd2");
                current_statement_begin__ = 98;
                if (as_bool(logical_lt(k, Kd2))) {
                    current_statement_begin__ = 98;
                    for (int kk = (k + 1); kk <= Kd2; ++kk) {
                        current_statement_begin__ = 99;
                        stan::math::assign(idp1, ((kk * 2) - 1));
                        current_statement_begin__ = 100;
                        stan::math::assign(idp2, (kk * 2));
                        current_statement_begin__ = 102;
                        stan::model::assign(Rd2, 
                                    stan::model::cons_list(stan::model::index_uni(idx1), stan::model::cons_list(stan::model::index_uni(idp1), stan::model::nil_index_list())), 
                                    (-(1) + (2 * get_base1(r_d2, kk, k, "r_d2", 1))), 
                                    "assigning variable Rd2");
                        current_statement_begin__ = 103;
                        stan::model::assign(Rd2, 
                                    stan::model::cons_list(stan::model::index_uni(idx2), stan::model::cons_list(stan::model::index_uni(idp2), stan::model::nil_index_list())), 
                                    (-(1) + (2 * get_base1(r_d2, kk, k, "r_d2", 1))), 
                                    "assigning variable Rd2");
                        current_statement_begin__ = 104;
                        stan::model::assign(Rd2, 
                                    stan::model::cons_list(stan::model::index_uni(idp1), stan::model::cons_list(stan::model::index_uni(idx1), stan::model::nil_index_list())), 
                                    (-(1) + (2 * get_base1(r_d2, kk, k, "r_d2", 1))), 
                                    "assigning variable Rd2");
                        current_statement_begin__ = 105;
                        stan::model::assign(Rd2, 
                                    stan::model::cons_list(stan::model::index_uni(idp2), stan::model::cons_list(stan::model::index_uni(idx2), stan::model::nil_index_list())), 
                                    (-(1) + (2 * get_base1(r_d2, kk, k, "r_d2", 1))), 
                                    "assigning variable Rd2");
                        current_statement_begin__ = 106;
                        stan::model::assign(Rd2, 
                                    stan::model::cons_list(stan::model::index_uni(idx1), stan::model::cons_list(stan::model::index_uni(idp2), stan::model::nil_index_list())), 
                                    (-(1) + (2 * get_base1(r_d2, k, kk, "r_d2", 1))), 
                                    "assigning variable Rd2");
                        current_statement_begin__ = 107;
                        stan::model::assign(Rd2, 
                                    stan::model::cons_list(stan::model::index_uni(idp2), stan::model::cons_list(stan::model::index_uni(idx1), stan::model::nil_index_list())), 
                                    (-(1) + (2 * get_base1(r_d2, k, kk, "r_d2", 1))), 
                                    "assigning variable Rd2");
                        current_statement_begin__ = 108;
                        stan::model::assign(Rd2, 
                                    stan::model::cons_list(stan::model::index_uni(idx2), stan::model::cons_list(stan::model::index_uni(idp1), stan::model::nil_index_list())), 
                                    (-(1) + (2 * get_base1(r_d2, k, kk, "r_d2", 1))), 
                                    "assigning variable Rd2");
                        current_statement_begin__ = 109;
                        stan::model::assign(Rd2, 
                                    stan::model::cons_list(stan::model::index_uni(idp1), stan::model::cons_list(stan::model::index_uni(idx2), stan::model::nil_index_list())), 
                                    (-(1) + (2 * get_base1(r_d2, k, kk, "r_d2", 1))), 
                                    "assigning variable Rd2");
                    }
                }
            }
            }
            current_statement_begin__ = 117;
            stan::math::assign(chol_d, diag_pre_multiply(S_d, cholesky_decompose(Rd2)));
            current_statement_begin__ = 119;
            stan::math::assign(chol_p, chol_r_p);
            {
            current_statement_begin__ = 123;
            int idx1(0);
            (void) idx1;  // dummy to suppress unused var warning
            stan::math::fill(idx1, std::numeric_limits<int>::min());
            current_statement_begin__ = 124;
            int idx2(0);
            (void) idx2;  // dummy to suppress unused var warning
            stan::math::fill(idx2, std::numeric_limits<int>::min());
            current_statement_begin__ = 126;
            for (int k = 1; k <= Kd2; ++k) {
                current_statement_begin__ = 127;
                stan::math::assign(idx1, ((k * 2) - 1));
                current_statement_begin__ = 128;
                stan::math::assign(idx2, (k * 2));
                current_statement_begin__ = 130;
                for (int d = 1; d <= Nd; ++d) {
                    current_statement_begin__ = 132;
                    stan::model::assign(Yd2hat, 
                                stan::model::cons_list(stan::model::index_uni(d), stan::model::cons_list(stan::model::index_uni(idx1), stan::model::nil_index_list())), 
                                ((get_base1(S_p, idx1, "S_p", 1) * get_base1(AP, get_base1(get_base1(IDp, d, "IDp", 1), 1, "IDp", 2), idx1, "AP", 1)) + (get_base1(S_p, idx2, "S_p", 1) * get_base1(AP, get_base1(get_base1(IDp, d, "IDp", 1), 2, "IDp", 2), idx2, "AP", 1))), 
                                "assigning variable Yd2hat");
                    current_statement_begin__ = 133;
                    stan::model::assign(Yd2hat, 
                                stan::model::cons_list(stan::model::index_uni(d), stan::model::cons_list(stan::model::index_uni(idx2), stan::model::nil_index_list())), 
                                ((get_base1(S_p, idx1, "S_p", 1) * get_base1(AP, get_base1(get_base1(IDp, d, "IDp", 1), 2, "IDp", 2), idx1, "AP", 1)) + (get_base1(S_p, idx2, "S_p", 1) * get_base1(AP, get_base1(get_base1(IDp, d, "IDp", 1), 1, "IDp", 2), idx2, "AP", 1))), 
                                "assigning variable Yd2hat");
                    current_statement_begin__ = 139;
                    stan::model::assign(augYd, 
                                stan::model::cons_list(stan::model::index_uni(d), stan::model::cons_list(stan::model::index_uni(idx1), stan::model::nil_index_list())), 
                                (stan::model::rvalue(augYd, stan::model::cons_list(stan::model::index_uni(d), stan::model::cons_list(stan::model::index_uni(idx1), stan::model::nil_index_list())), "augYd") + get_base1(Mvec, k, "Mvec", 1)), 
                                "assigning variable augYd");
                    current_statement_begin__ = 140;
                    stan::model::assign(augYd, 
                                stan::model::cons_list(stan::model::index_uni(d), stan::model::cons_list(stan::model::index_uni(idx2), stan::model::nil_index_list())), 
                                (stan::model::rvalue(augYd, stan::model::cons_list(stan::model::index_uni(d), stan::model::cons_list(stan::model::index_uni(idx2), stan::model::nil_index_list())), "augYd") + get_base1(Mvec, k, "Mvec", 1)), 
                                "assigning variable augYd");
                }
            }
            }
            if (!include_gqs__ && !include_tparams__) return;
            // validate transformed parameters
            const char* function__ = "validate transformed params";
            (void) function__;  // dummy to suppress unused var warning
            // write transformed parameters
            if (include_tparams__) {
                size_t Yd2hat_j_2_max__ = allKd;
                size_t Yd2hat_j_1_max__ = Nd;
                for (size_t j_2__ = 0; j_2__ < Yd2hat_j_2_max__; ++j_2__) {
                    for (size_t j_1__ = 0; j_1__ < Yd2hat_j_1_max__; ++j_1__) {
                        vars__.push_back(Yd2hat(j_1__, j_2__));
                    }
                }
                size_t S_d_j_1_max__ = allKd;
                for (size_t j_1__ = 0; j_1__ < S_d_j_1_max__; ++j_1__) {
                    vars__.push_back(S_d(j_1__));
                }
                size_t Rd2_j_2_max__ = allKd;
                size_t Rd2_j_1_max__ = allKd;
                for (size_t j_2__ = 0; j_2__ < Rd2_j_2_max__; ++j_2__) {
                    for (size_t j_1__ = 0; j_1__ < Rd2_j_1_max__; ++j_1__) {
                        vars__.push_back(Rd2(j_1__, j_2__));
                    }
                }
                size_t chol_d_j_2_max__ = allKd;
                size_t chol_d_j_1_max__ = allKd;
                for (size_t j_2__ = 0; j_2__ < chol_d_j_2_max__; ++j_2__) {
                    for (size_t j_1__ = 0; j_1__ < chol_d_j_1_max__; ++j_1__) {
                        vars__.push_back(chol_d(j_1__, j_2__));
                    }
                }
                size_t chol_p_j_2_max__ = allKp;
                size_t chol_p_j_1_max__ = allKp;
                for (size_t j_2__ = 0; j_2__ < chol_p_j_2_max__; ++j_2__) {
                    for (size_t j_1__ = 0; j_1__ < chol_p_j_1_max__; ++j_1__) {
                        vars__.push_back(chol_p(j_1__, j_2__));
                    }
                }
                size_t augYd_j_2_max__ = allKd;
                size_t augYd_j_1_max__ = Nd;
                for (size_t j_2__ = 0; j_2__ < augYd_j_2_max__; ++j_2__) {
                    for (size_t j_1__ = 0; j_1__ < augYd_j_1_max__; ++j_1__) {
                        vars__.push_back(augYd(j_1__, j_2__));
                    }
                }
                size_t augYp_j_2_max__ = allKp;
                size_t augYp_j_1_max__ = Np;
                for (size_t j_2__ = 0; j_2__ < augYp_j_2_max__; ++j_2__) {
                    for (size_t j_1__ = 0; j_1__ < augYp_j_1_max__; ++j_1__) {
                        vars__.push_back(augYp(j_1__, j_2__));
                    }
                }
            }
            if (!include_gqs__) return;
            // declare and define generated quantities
            current_statement_begin__ = 178;
            validate_non_negative_index("Yd2e", "Nd", Nd);
            validate_non_negative_index("Yd2e", "allKd", allKd);
            Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic> Yd2e(Nd, allKd);
            stan::math::initialize(Yd2e, DUMMY_VAR__);
            stan::math::fill(Yd2e, DUMMY_VAR__);
            current_statement_begin__ = 179;
            validate_non_negative_index("Rp", "allKp", allKp);
            validate_non_negative_index("Rp", "allKp", allKp);
            Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic> Rp(allKp, allKp);
            stan::math::initialize(Rp, DUMMY_VAR__);
            stan::math::fill(Rp, DUMMY_VAR__);
            current_statement_begin__ = 183;
            validate_non_negative_index("Rsq", "Kd2", Kd2);
            validate_non_negative_index("Rsq", "3", 3);
            Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic> Rsq(Kd2, 3);
            stan::math::initialize(Rsq, DUMMY_VAR__);
            stan::math::fill(Rsq, DUMMY_VAR__);
            // generated quantities statements
            {
            current_statement_begin__ = 187;
            validate_non_negative_index("vars", "Kd2", Kd2);
            validate_non_negative_index("vars", "3", 3);
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, Eigen::Dynamic> vars(Kd2, 3);
            stan::math::initialize(vars, DUMMY_VAR__);
            stan::math::fill(vars, DUMMY_VAR__);
            current_statement_begin__ = 188;
            validate_non_negative_index("totals", "Kd2", Kd2);
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> totals(Kd2);
            stan::math::initialize(totals, DUMMY_VAR__);
            stan::math::fill(totals, DUMMY_VAR__);
            current_statement_begin__ = 190;
            for (int k = 1; k <= Kd2; ++k) {
                current_statement_begin__ = 191;
                stan::model::assign(vars, 
                            stan::model::cons_list(stan::model::index_uni(k), stan::model::cons_list(stan::model::index_uni(1), stan::model::nil_index_list())), 
                            square(get_base1(S_p, ((2 * k) - 1), "S_p", 1)), 
                            "assigning variable vars");
                current_statement_begin__ = 192;
                stan::model::assign(vars, 
                            stan::model::cons_list(stan::model::index_uni(k), stan::model::cons_list(stan::model::index_uni(2), stan::model::nil_index_list())), 
                            square(get_base1(S_p, (2 * k), "S_p", 1)), 
                            "assigning variable vars");
                current_statement_begin__ = 193;
                stan::model::assign(vars, 
                            stan::model::cons_list(stan::model::index_uni(k), stan::model::cons_list(stan::model::index_uni(3), stan::model::nil_index_list())), 
                            square(get_base1(s_rr, k, "s_rr", 1)), 
                            "assigning variable vars");
                current_statement_begin__ = 195;
                stan::model::assign(totals, 
                            stan::model::cons_list(stan::model::index_uni(k), stan::model::nil_index_list()), 
                            sum(stan::model::rvalue(vars, stan::model::cons_list(stan::model::index_uni(k), stan::model::cons_list(stan::model::index_omni(), stan::model::nil_index_list())), "vars")), 
                            "assigning variable totals");
                current_statement_begin__ = 196;
                stan::model::assign(Rsq, 
                            stan::model::cons_list(stan::model::index_uni(k), stan::model::cons_list(stan::model::index_omni(), stan::model::nil_index_list())), 
                            elt_divide(stan::model::rvalue(vars, stan::model::cons_list(stan::model::index_uni(k), stan::model::cons_list(stan::model::index_omni(), stan::model::nil_index_list())), "vars"), get_base1(totals, k, "totals", 1)), 
                            "assigning variable Rsq");
            }
            }
            current_statement_begin__ = 203;
            stan::math::assign(Yd2e, subtract(augYd, Yd2hat));
            current_statement_begin__ = 206;
            stan::math::assign(Rp, multiply_lower_tri_self_transpose(chol_r_p));
            // validate, write generated quantities
            current_statement_begin__ = 178;
            size_t Yd2e_j_2_max__ = allKd;
            size_t Yd2e_j_1_max__ = Nd;
            for (size_t j_2__ = 0; j_2__ < Yd2e_j_2_max__; ++j_2__) {
                for (size_t j_1__ = 0; j_1__ < Yd2e_j_1_max__; ++j_1__) {
                    vars__.push_back(Yd2e(j_1__, j_2__));
                }
            }
            current_statement_begin__ = 179;
            size_t Rp_j_2_max__ = allKp;
            size_t Rp_j_1_max__ = allKp;
            for (size_t j_2__ = 0; j_2__ < Rp_j_2_max__; ++j_2__) {
                for (size_t j_1__ = 0; j_1__ < Rp_j_1_max__; ++j_1__) {
                    vars__.push_back(Rp(j_1__, j_2__));
                }
            }
            current_statement_begin__ = 183;
            size_t Rsq_j_2_max__ = 3;
            size_t Rsq_j_1_max__ = Kd2;
            for (size_t j_2__ = 0; j_2__ < Rsq_j_2_max__; ++j_2__) {
                for (size_t j_1__ = 0; j_1__ < Rsq_j_1_max__; ++j_1__) {
                    vars__.push_back(Rsq(j_1__, j_2__));
                }
            }
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
    }
    template <typename RNG>
    void write_array(RNG& base_rng,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                     bool include_tparams = true,
                     bool include_gqs = true,
                     std::ostream* pstream = 0) const {
      std::vector<double> params_r_vec(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r_vec[i] = params_r(i);
      std::vector<double> vars_vec;
      std::vector<int> params_i_vec;
      write_array(base_rng, params_r_vec, params_i_vec, vars_vec, include_tparams, include_gqs, pstream);
      vars.resize(vars_vec.size());
      for (int i = 0; i < vars.size(); ++i)
        vars(i) = vars_vec[i];
    }
    std::string model_name() const {
        return "model_RR_con_comp_g1";
    }
    void constrained_param_names(std::vector<std::string>& param_names__,
                                 bool include_tparams__ = true,
                                 bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        size_t Mvec_j_1_max__ = Kd2;
        for (size_t j_1__ = 0; j_1__ < Mvec_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "Mvec" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t s_rr_j_1_max__ = Kd2;
        for (size_t j_1__ = 0; j_1__ < s_rr_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "s_rr" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t S_p_j_1_max__ = allKp;
        for (size_t j_1__ = 0; j_1__ < S_p_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "S_p" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t chol_r_p_j_2_max__ = allKp;
        size_t chol_r_p_j_1_max__ = allKp;
        for (size_t j_2__ = 0; j_2__ < chol_r_p_j_2_max__; ++j_2__) {
            for (size_t j_1__ = 0; j_1__ < chol_r_p_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "chol_r_p" << '.' << j_1__ + 1 << '.' << j_2__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
        }
        size_t r_d2_j_2_max__ = Kd2;
        size_t r_d2_j_1_max__ = Kd2;
        for (size_t j_2__ = 0; j_2__ < r_d2_j_2_max__; ++j_2__) {
            for (size_t j_1__ = 0; j_1__ < r_d2_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "r_d2" << '.' << j_1__ + 1 << '.' << j_2__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
        }
        size_t AP_j_2_max__ = (2 * Kd2);
        size_t AP_j_1_max__ = Np;
        for (size_t j_2__ = 0; j_2__ < AP_j_2_max__; ++j_2__) {
            for (size_t j_1__ = 0; j_1__ < AP_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "AP" << '.' << j_1__ + 1 << '.' << j_2__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
        }
        if (!include_gqs__ && !include_tparams__) return;
        if (include_tparams__) {
            size_t Yd2hat_j_2_max__ = allKd;
            size_t Yd2hat_j_1_max__ = Nd;
            for (size_t j_2__ = 0; j_2__ < Yd2hat_j_2_max__; ++j_2__) {
                for (size_t j_1__ = 0; j_1__ < Yd2hat_j_1_max__; ++j_1__) {
                    param_name_stream__.str(std::string());
                    param_name_stream__ << "Yd2hat" << '.' << j_1__ + 1 << '.' << j_2__ + 1;
                    param_names__.push_back(param_name_stream__.str());
                }
            }
            size_t S_d_j_1_max__ = allKd;
            for (size_t j_1__ = 0; j_1__ < S_d_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "S_d" << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
            size_t Rd2_j_2_max__ = allKd;
            size_t Rd2_j_1_max__ = allKd;
            for (size_t j_2__ = 0; j_2__ < Rd2_j_2_max__; ++j_2__) {
                for (size_t j_1__ = 0; j_1__ < Rd2_j_1_max__; ++j_1__) {
                    param_name_stream__.str(std::string());
                    param_name_stream__ << "Rd2" << '.' << j_1__ + 1 << '.' << j_2__ + 1;
                    param_names__.push_back(param_name_stream__.str());
                }
            }
            size_t chol_d_j_2_max__ = allKd;
            size_t chol_d_j_1_max__ = allKd;
            for (size_t j_2__ = 0; j_2__ < chol_d_j_2_max__; ++j_2__) {
                for (size_t j_1__ = 0; j_1__ < chol_d_j_1_max__; ++j_1__) {
                    param_name_stream__.str(std::string());
                    param_name_stream__ << "chol_d" << '.' << j_1__ + 1 << '.' << j_2__ + 1;
                    param_names__.push_back(param_name_stream__.str());
                }
            }
            size_t chol_p_j_2_max__ = allKp;
            size_t chol_p_j_1_max__ = allKp;
            for (size_t j_2__ = 0; j_2__ < chol_p_j_2_max__; ++j_2__) {
                for (size_t j_1__ = 0; j_1__ < chol_p_j_1_max__; ++j_1__) {
                    param_name_stream__.str(std::string());
                    param_name_stream__ << "chol_p" << '.' << j_1__ + 1 << '.' << j_2__ + 1;
                    param_names__.push_back(param_name_stream__.str());
                }
            }
            size_t augYd_j_2_max__ = allKd;
            size_t augYd_j_1_max__ = Nd;
            for (size_t j_2__ = 0; j_2__ < augYd_j_2_max__; ++j_2__) {
                for (size_t j_1__ = 0; j_1__ < augYd_j_1_max__; ++j_1__) {
                    param_name_stream__.str(std::string());
                    param_name_stream__ << "augYd" << '.' << j_1__ + 1 << '.' << j_2__ + 1;
                    param_names__.push_back(param_name_stream__.str());
                }
            }
            size_t augYp_j_2_max__ = allKp;
            size_t augYp_j_1_max__ = Np;
            for (size_t j_2__ = 0; j_2__ < augYp_j_2_max__; ++j_2__) {
                for (size_t j_1__ = 0; j_1__ < augYp_j_1_max__; ++j_1__) {
                    param_name_stream__.str(std::string());
                    param_name_stream__ << "augYp" << '.' << j_1__ + 1 << '.' << j_2__ + 1;
                    param_names__.push_back(param_name_stream__.str());
                }
            }
        }
        if (!include_gqs__) return;
        size_t Yd2e_j_2_max__ = allKd;
        size_t Yd2e_j_1_max__ = Nd;
        for (size_t j_2__ = 0; j_2__ < Yd2e_j_2_max__; ++j_2__) {
            for (size_t j_1__ = 0; j_1__ < Yd2e_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "Yd2e" << '.' << j_1__ + 1 << '.' << j_2__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
        }
        size_t Rp_j_2_max__ = allKp;
        size_t Rp_j_1_max__ = allKp;
        for (size_t j_2__ = 0; j_2__ < Rp_j_2_max__; ++j_2__) {
            for (size_t j_1__ = 0; j_1__ < Rp_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "Rp" << '.' << j_1__ + 1 << '.' << j_2__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
        }
        size_t Rsq_j_2_max__ = 3;
        size_t Rsq_j_1_max__ = Kd2;
        for (size_t j_2__ = 0; j_2__ < Rsq_j_2_max__; ++j_2__) {
            for (size_t j_1__ = 0; j_1__ < Rsq_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "Rsq" << '.' << j_1__ + 1 << '.' << j_2__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
        }
    }
    void unconstrained_param_names(std::vector<std::string>& param_names__,
                                   bool include_tparams__ = true,
                                   bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        size_t Mvec_j_1_max__ = Kd2;
        for (size_t j_1__ = 0; j_1__ < Mvec_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "Mvec" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t s_rr_j_1_max__ = Kd2;
        for (size_t j_1__ = 0; j_1__ < s_rr_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "s_rr" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t S_p_j_1_max__ = allKp;
        for (size_t j_1__ = 0; j_1__ < S_p_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "S_p" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t chol_r_p_j_1_max__ = ((allKp * (allKp - 1)) / 2);
        for (size_t j_1__ = 0; j_1__ < chol_r_p_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "chol_r_p" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t r_d2_j_2_max__ = Kd2;
        size_t r_d2_j_1_max__ = Kd2;
        for (size_t j_2__ = 0; j_2__ < r_d2_j_2_max__; ++j_2__) {
            for (size_t j_1__ = 0; j_1__ < r_d2_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "r_d2" << '.' << j_1__ + 1 << '.' << j_2__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
        }
        size_t AP_j_2_max__ = (2 * Kd2);
        size_t AP_j_1_max__ = Np;
        for (size_t j_2__ = 0; j_2__ < AP_j_2_max__; ++j_2__) {
            for (size_t j_1__ = 0; j_1__ < AP_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "AP" << '.' << j_1__ + 1 << '.' << j_2__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
        }
        if (!include_gqs__ && !include_tparams__) return;
        if (include_tparams__) {
            size_t Yd2hat_j_2_max__ = allKd;
            size_t Yd2hat_j_1_max__ = Nd;
            for (size_t j_2__ = 0; j_2__ < Yd2hat_j_2_max__; ++j_2__) {
                for (size_t j_1__ = 0; j_1__ < Yd2hat_j_1_max__; ++j_1__) {
                    param_name_stream__.str(std::string());
                    param_name_stream__ << "Yd2hat" << '.' << j_1__ + 1 << '.' << j_2__ + 1;
                    param_names__.push_back(param_name_stream__.str());
                }
            }
            size_t S_d_j_1_max__ = allKd;
            for (size_t j_1__ = 0; j_1__ < S_d_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "S_d" << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
            size_t Rd2_j_2_max__ = allKd;
            size_t Rd2_j_1_max__ = allKd;
            for (size_t j_2__ = 0; j_2__ < Rd2_j_2_max__; ++j_2__) {
                for (size_t j_1__ = 0; j_1__ < Rd2_j_1_max__; ++j_1__) {
                    param_name_stream__.str(std::string());
                    param_name_stream__ << "Rd2" << '.' << j_1__ + 1 << '.' << j_2__ + 1;
                    param_names__.push_back(param_name_stream__.str());
                }
            }
            size_t chol_d_j_2_max__ = allKd;
            size_t chol_d_j_1_max__ = allKd;
            for (size_t j_2__ = 0; j_2__ < chol_d_j_2_max__; ++j_2__) {
                for (size_t j_1__ = 0; j_1__ < chol_d_j_1_max__; ++j_1__) {
                    param_name_stream__.str(std::string());
                    param_name_stream__ << "chol_d" << '.' << j_1__ + 1 << '.' << j_2__ + 1;
                    param_names__.push_back(param_name_stream__.str());
                }
            }
            size_t chol_p_j_2_max__ = allKp;
            size_t chol_p_j_1_max__ = allKp;
            for (size_t j_2__ = 0; j_2__ < chol_p_j_2_max__; ++j_2__) {
                for (size_t j_1__ = 0; j_1__ < chol_p_j_1_max__; ++j_1__) {
                    param_name_stream__.str(std::string());
                    param_name_stream__ << "chol_p" << '.' << j_1__ + 1 << '.' << j_2__ + 1;
                    param_names__.push_back(param_name_stream__.str());
                }
            }
            size_t augYd_j_2_max__ = allKd;
            size_t augYd_j_1_max__ = Nd;
            for (size_t j_2__ = 0; j_2__ < augYd_j_2_max__; ++j_2__) {
                for (size_t j_1__ = 0; j_1__ < augYd_j_1_max__; ++j_1__) {
                    param_name_stream__.str(std::string());
                    param_name_stream__ << "augYd" << '.' << j_1__ + 1 << '.' << j_2__ + 1;
                    param_names__.push_back(param_name_stream__.str());
                }
            }
            size_t augYp_j_2_max__ = allKp;
            size_t augYp_j_1_max__ = Np;
            for (size_t j_2__ = 0; j_2__ < augYp_j_2_max__; ++j_2__) {
                for (size_t j_1__ = 0; j_1__ < augYp_j_1_max__; ++j_1__) {
                    param_name_stream__.str(std::string());
                    param_name_stream__ << "augYp" << '.' << j_1__ + 1 << '.' << j_2__ + 1;
                    param_names__.push_back(param_name_stream__.str());
                }
            }
        }
        if (!include_gqs__) return;
        size_t Yd2e_j_2_max__ = allKd;
        size_t Yd2e_j_1_max__ = Nd;
        for (size_t j_2__ = 0; j_2__ < Yd2e_j_2_max__; ++j_2__) {
            for (size_t j_1__ = 0; j_1__ < Yd2e_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "Yd2e" << '.' << j_1__ + 1 << '.' << j_2__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
        }
        size_t Rp_j_2_max__ = allKp;
        size_t Rp_j_1_max__ = allKp;
        for (size_t j_2__ = 0; j_2__ < Rp_j_2_max__; ++j_2__) {
            for (size_t j_1__ = 0; j_1__ < Rp_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "Rp" << '.' << j_1__ + 1 << '.' << j_2__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
        }
        size_t Rsq_j_2_max__ = 3;
        size_t Rsq_j_1_max__ = Kd2;
        for (size_t j_2__ = 0; j_2__ < Rsq_j_2_max__; ++j_2__) {
            for (size_t j_1__ = 0; j_1__ < Rsq_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "Rsq" << '.' << j_1__ + 1 << '.' << j_2__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
        }
    }
}; // model
}  // namespace
typedef model_RR_con_comp_g1_namespace::model_RR_con_comp_g1 stan_model;
#ifndef USING_R
stan::model::model_base& new_model(
        stan::io::var_context& data_context,
        unsigned int seed,
        std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
#endif
#endif
